# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Fyne
email: info@fyne.io
description: >- # this means to ignore newlines until "baseurl:"
  Website for the Fyne app development framework.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://fyne.io/" # the base hostname & protocol for your site, e.g. http://example.com

headline: Your beautiful new<br>open source desktop
tagline: >- # multiline
  We're building a modern application framework and desktop environment<br>
  focussed on design, usability and ease of development and distribution.<br>
  Best of all it's open source and free to use!

blog-headline: The latest news from the Fyne community
blog-tagline: Keep up to date wih everything we're working on and how the project is shaping up.

twitter_username: fyne_io
github_username: fyne-io
freenode_channel: fyne

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
github: [metadata]

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

theme: jekyll-theme-minimal
